### PR TITLE
Fix warnings for deprecated usages of trim_{left,right}_matches.

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks!  This raises the MSRV to 1.30, though Alex says he's fine with "current stable-1".

**Comment by ErichDonGubler** [comment]
Huh? So far as I can tell, this crate is already MSRV 1.30 because [the `$crate` prefix is being used](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-with-crate-prefix). Am I missing something?

**Comment by ehuss** [comment]
For this one, trim_end/trim_start weren't stabilized until 1.30.

**Comment by ErichDonGubler** [comment]
Understood. Thanks!

**Pull request merged**
