### PR TITLE
Support deserializing from other integer types

### PR DESCRIPTION
**Pull request by kornelski**
Fixes https://github.com/serde-rs/json/issues/471

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could a test be added for this as well?

**Comment by kornelski** [comment]
I've ran into this via `serde_json`, but I'm not sure if you want to have it as a dev dependency.  I'm not familiar enough with serde's internals to mock it out.

**Comment by alexcrichton** [comment]
Ah sure yeah, adding such a dep seems fine by me!

**Comment by kornelski** [comment]
Ok, added test.

**Comment by Michael-F-Bryan** [comment]
I just ran into this with `mdbook` and `mdbook-linkcheck` (in particular, [`mdbook::config::Search`]). 

It looks like the last release for `toml` was in April, is there any chance a patch release could be added so we have access to this?

[`mdbook::config::Search`]: https://docs.rs/mdbook/0.2.1/mdbook/config/struct.Search.html

**Comment by alexcrichton** [comment]
Ah sorry about that, published now!

**Comment by ehuss** [comment]
@alexcrichton The 0.4.7 release brings in a lot of changes compared to 0.4.6, including the new 0.5 syntax. I'm concerned that may bring in unexpected changes to people depending on "0.4". Is that OK?

**Comment by alexcrichton** [comment]
@ehuss ah true, I forgot about that! I do think though that we'll probably want to stick to the 0.4 chain if we can (as it's all "largely backwards compatible" anyway I believe)

If any problems are encountered though we can republish as 0.5

**Pull request merged**
