### PR TITLE
0.5: Support dotted keys.

### PR DESCRIPTION
**Pull request by ehuss**
cc #224

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wouldn't worry too much about errors and spans, we can always try to fix those up later I think. Should it be possible to use these keys to insert into normal tables as well though? Something like:

```toml
a.b = 1
[a.c]
d = 3

**Comment by ehuss** [comment]
Good question.  There's a lot of discussion on the toml issues about when tables should be open/closed, but it doesn't look like there is much consensus. I'll ask them about that case.

What do you think about keeping it conservative for now, and expanding support later if that's the direction TOML wants to go?

I'd also be fine with delaying this PR until they decide on these issues.  This is by far the biggest change, and probably going to be controversial to some.

**Comment by alexcrichton** [comment]
I'd be fine with either the route of holding off until we hear back on the issue or adding the conservative pieces here. We could also add support but require a flag to turn it on in the parser perhaps?

**Comment by ehuss** [comment]
I'm keen to wait for clarity on the spec.  I'll circle back once I have a better understanding how it should work.

**Comment by ehuss** [comment]
I've pushed a small change to add a further restriction that dotted keys can't insert into previous inline tables.

I've been thinking about this for a while.  I feel like it would be best to initially be conservative and don't allow the three table types to intermix.  The limitations can be removed later if there are compelling reasons or use cases.  I think it will be easier to relax the restrictions later than to initially start with something too permissive.

**Comment by alexcrichton** [comment]
Sounds great to me, thanks!

**Pull request merged**
