### PR TITLE
Issue 255: Externally tagged enum deserialization

### PR DESCRIPTION
**Pull request by azriel91**
cc: #225, #222

~~The tuple variant hasn't been implemented yet, I'm having trouble figuring it out.~~
See #225 for ongoing discussion -- what should / should not be supported.

Short, the following TOML:

```toml
plain = "Plain"
plain_table = { Plain = {} }
tuple = { Tuple = { 0 = 123, 1 = true } }
struct = { Struct = { value = 123 } }
newtype = { NewType = "value" }
my_enum = [
    { Plain = {} },
    { Tuple = { 0 = 123, 1 = true } },
    { NewType = "value" },
    { Struct = { value = 123 } }
]
```

with the following types:

```rust
#[derive(Debug, Deserialize)]
struct Config {
    plain: MyEnum,
    plain_table: MyEnum,
    tuple: MyEnum,
    #[serde(rename = "struct")]
    structv: MyEnum,
    newtype: MyEnum,
    my_enum: Vec<MyEnum>,
}

#[derive(Debug, Deserialize)]
enum MyEnum {
    Plain,
    Tuple(i64, bool),
    NewType(String),
    Struct { value: i64 },
}
```

deserializes to:

```rust
Config {
    plain: Plain,
    plain_table: Plain,
    tuple: Tuple(
        123,
        true
    ),
    structv: Struct {
        value: 123
    },
    newtype: NewType(
        "value"
    ),
    my_enum: [
        Plain,
        Tuple(
            123,
            true
        ),
        NewType(
            "value"
        ),
        Struct {
            value: 123
        }
    ]
}
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I don't personally have too many opinions about how we should map enums to toml, but I think we can probably pretty closely follow `serde_json` in this regard? Would it be possible to just clone whatever `serde_json` does for all these serializations?

**Comment by azriel91** [comment]
Finally got round to this, `serde_json` serializes the value like this:

<details>
<summary>json serialized</summary>

```json
{
    "plain": "Plain",
    "plain_table": "Plain",
    "tuple": {
        "Tuple": [
            -1,
            false
        ]
    },
    "struct": {
        "Struct": {
            "value": -1
        }
    },
    "newtype": {
        "NewType": "abc"
    },
    "my_enum": [
        "Plain",
        {
            "Tuple": [
                -1,
                false
            ]
        },
        {
            "NewType": "abc"
        },
        {
            "Struct": {
                "value": -1
            }
        }
    ]
}
```
</details>

The structure is similar, the differences:

* JSON array allows you to have mixed types, so
    - Tuples are represented using arrays in JSON. (mixed types are invalid in TOML, so we need to use a TOML table)
    - Array of enum variants is valid in JSON: `["Plain", { "Tuple": [ -1, false ] }]`
* In TOML it would be ergonomic to represent plain enum variants as `"String"`, but represented as a TOML table when used in an array

I'll work on getting serialization to work that way, since it's the closest we can get to JSON

**Comment by azriel91** [comment]
I've gotten deserialization matching the above (and tested! yay). For serialization, the tuple variant currently emits a toml array, which is invalid if you have a tuple variant with different types.

I'm not sure whether it's okay to break backwards compatibility and emit a table -- should I:

* **A:** Try and be clever and emit an array if the tuple fields are the same type, and a table if they are different types?
* **B:** Make it always emit an inline table

**Comment by azriel91** [comment]
I'll push serialization to a separate branch &ndash; I haven't managed to get it *correct*, let alone clean. In case you're happy with having deserialization without serialization as a partial state.

**Comment by alexcrichton** [comment]
Oh dear sorry about that @Aaronepower! I'm somewhat low on reviewing bandwidth for this at the moment, so some assistance in reviewing this would be greatly appreciated!

**Comment by Aaronepower** [comment]
@alexcrichton Sure no problem!

@azriel91 There seem to be a lot of unrelated style changes to the codebase. (Adding semicolons, changes the formatting of arguments, extra commas, etc.) Are you perhaps using rustfmt? I think removing those tidy ups would make it easier to see the changes. For example there's 940 changes in `src/de.rs`, but as far as I can tell there's actually 144 lines that aren't tidying up the code.

**Comment by azriel91** [comment]
Yeap, the first commit is purely rustfmt, so the relevant diff would be the ones after that.
I can push over this without that if you prefer

**Comment by Aaronepower** [comment]
@azriel91 If you could that would be very helpful. I've found that trying to review through individual commits is a lot of work as you have to keep track of the code from previous commits as well new code.

**Comment by azriel91** [comment]
There we go

**Comment by Aaronepower** [comment]
@azriel91 Generally this looks good to me. Can you add some tests that should always fail with this kind of deserialisation?

**Comment by azriel91** [comment]
"Yes!", but first I have to understand what you mean 😅. There's these possible meanings:

* array of tables: unsupported but potentially supported later (implement as "pending")
* invalid variant / fields in variants (should panic, useful error message)
* something else?

**Comment by azriel91** [comment]
I've pushed tests + changes for the first two bullet points

**Comment by Aaronepower** [comment]
@azriel91 It seems that last commit has caused some errors in the CI.

**Comment by azriel91** [comment]
ah yeap, only noticed it yesterday, pushed a quick fix 🤞

**Comment by Aaronepower** [comment]
@alexcrichton Have a look yourself, but it looks good to me.

**Comment by alexcrichton** [comment]
Er sorry for the delay!

I unfortunately still don't really understand most of this code, the serde implementation has always been opaque at best to me. I'll trust y'all though!

**Pull request merged**
