### PR TITLE
Public datetime structs followups

### PR DESCRIPTION
**Pull request by not-my-profile**
Btw I'd love to use #439 in a project I want to publish on crates.io, would it be possible to release a new version of the `toml` crate?

### CODE REVIEW

**Comment by ehuss** [comment]
Can you say why this is adding `PartialOrd`?  That seems precarious, as there can be ambiguities or other confusions. For example, the ordering of a `Datetime` with just a date versus one with just a time. Is there precedent in other libraries for this?  `Value` itself is not sortable, so it is not clear why this is being added.

**Comment by not-my-profile** [comment]
I did not add `PartialOrd` for `Datetime` to avoid that very ambiguity. I only added it for `Date` and `Time` for which it is unambiguous.

**Comment by ehuss** [comment]
I see, but can you explain what your use case is?  It is helpful when submitting a PR to explain what it is changing and importantly why it is changing.

**Comment by not-my-profile** [comment]
I am working on a static-site generator where each page can define metadata in TOML. That metadata can then be queried via a query language to e.g. sort pages by date. I am using `toml::Value` to store the metadata (since it can be arbitrary). I don't mind that `Value` is not sortable since I only want to allow comparisons between values of the same type anyway.

If `Date` and `Time` derive `PartialOrd` implementing that comparison becomes a bit more convenient for me.

Even better would be if `Datetime` was split as suggested in https://github.com/alexcrichton/toml-rs/issues/159#issuecomment-463732912 and all of these would implement `PartialOrd`. Should I attempt that instead?

**Comment by not-my-profile** [comment]
To be fair I think that publicizing the `Datetime` struct as has been done in #431 is a bit weird because it allows the construction of `toml::Value`s that aren't valid TOML:

```rust
    let val = toml::Value::Table(
        vec![(
            "test".into(),
            toml::Value::Datetime(Datetime {
                date: None,
                time: None,
                offset: None,
            }),
        )]
        .into_iter()
        .collect(),
    );
    let out = toml::to_string(&val).unwrap();
    println!("{:?}", out);
```

prints `"test = \n"` ...

**Comment by epage** [comment]
toml-rs has moved to https://github.com/toml-rs/toml_edit.  Feel free to rebase your PR against that repo and open a new issue there.

**Pull request closed without merging**
